# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@vue/cli"
        versions: [">=5.0.0"]
      - dependency-name: "@vue/cli-plugin-babel"
        versions: [">=5.0.0"]
      - dependency-name: "@vue/cli-plugin-eslint"
        versions: [">=5.0.0"]
      - dependency-name: "@vue/cli-plugin-pwa"
        versions: [">=5.0.0"]
      - dependency-name: "@vue/cli-plugin-router"
        versions: [">=5.0.0"]
      - dependency-name: "@vue/cli-plugin-typescript"
        versions: [">=5.0.0"]
      - dependency-name: "@vue/cli-service"
        versions: [">=5.0.0"]
      - dependency-name: "electron"
        versions: [">=23.0.0"]
      - dependency-name: "vue"
        versions: [">=3.0.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
